<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Entity\ModuleDescription;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {

        $formations = $this->getDoctrine()->getManager()->getRepository(Formation::class)->requestAccueil();
        return $this->render('default/index.html.twig', ['formations' => $formations]);
    }

    protected function render(string $view, array $parameters = [], Response $response = null): Response
    {
        $headerTab = [
            'headerModule' => $this->getDoctrine()->getManager()->getRepository(Formation::class)
        ];

        return parent::render($view, array_merge($headerTab, $parameters), $response); // TODO: Change the autogenerated stub
    }
}
